apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: examen2-cluster
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::888105960225:role/LabRole

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      instanceRoleARN: arn:aws:iam::888105960225:role/LabRole