apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt-worker
  template:
    metadata:
      labels:
        app: receipt-worker
    spec:
      containers:
        - name: receipt-worker
          image: tuusuario/examen2-receipt-worker:latest
          envFrom:
            - configMapRef:
                name: examen2-config